# This file was created by adamjohnson.
# No Cargo.lock.
[package]
name = "adamjohnson-gif"
version = "0.1.0"
authors = ["Adam Johnson <llamaguy82@gmail.com>"]
edition = "2024"
description = "Config files for my GitHub profile."
license = "GPL-3.0"
readme = "README.md"

[dependencies]
ascii = "1.1"
rustix = "1.1.4"
validator = { version = "0.20", features = ["derive"] }
anstyle = "1.0.14"
iascii = { version = "0.1.1" }
